version: '3.8'
services:
  webapp_stores:
      build:
        context: ./
        target: app
      container_name: stores
      restart: unless-stopped
      volumes:
        - ./:/app
#      ports:
#        - "5000:5000"
      expose:
        - 5000
      command: gunicorn --bind 0.0.0.0:5000 manage:app #&& celery -A tasks worker --loglevel=INFO && celery -A tasks beat
      links:
        - redis
      env_file:
        - ./.env
      networks:
        - my-network
#      depends_on:
#        - redis

  nginx:
    build:
      context: ./
      target: nginx
    ports:
      - 1337:80
    networks:
      - my-network
    links:
      - webapp_stores
    depends_on:
      - webapp_stores

  celery:
    build:
        context: .
        target: celery
    container_name: celery
    restart: always
    environment:
#                - CELERY_BROKER_URL=redis://redis:6379/
        - FLASK_APP=webapp_stores
    networks:
        - my-network
    links:
        - redis
    depends_on:
        - redis
        - webapp_stores

#  flower:
#    image: mher/flower:latest
##    networks: my_network
#    command: flower
#    ports:
#      - "5555:5555"
#    links:
#      - webapp_stores
#    depends_on:
#      - webapp_stores
#    networks:
#      - my-network
  redis:
    image: "redis:alpine"
    networks:
      - my-network
networks:
    my-network: