version: '3'
services:

  celery: celery:latest
    container_name: celeryd
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL: redis://redis:6379/
      - FLASK_APP: webapp_stores
    command:
      - celery -A tasks beat
      - celery -A tasks worker
  flower:
    image: mher/flower:latest
    container_name: flower
    command: celery flower -A tasks
    ports:
      - "5555:5555"
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  webapp_stores:
    build:
      context: ./
    container_name: stores
    restart: unless-stopped
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celery
      - flower