"""add col search

Revision ID: 8e529df69087
Revises: b49cfbeb0713
Create Date: 2020-07-13 12:45:28.903362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e529df69087'
down_revision = 'b49cfbeb0713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('search', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_search'), 'user', ['search'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_search'), table_name='user')
    op.drop_column('user', 'search')
    # ### end Alembic commands ###
