"""send_mail add

Revision ID: b49cfbeb0713
Revises: 00b9dc914bdf
Create Date: 2020-07-05 13:01:39.041001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49cfbeb0713'
down_revision = '00b9dc914bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('send_mail', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'send_mail')
    # ### end Alembic commands ###
